export const multi = {
  en: {
    "viewMode": "View Mode",
    "addNew": "Add New",
    "viewContents": "View Contents",
    "inputURL":"Enter the URL of text",
    "textTitle": "Text Title",
    "enTitle":"Enter the title in English",
    "frTitle":"Enter the title in French",
    "esTitle":"Enter the title in Spanish",
    "enLabel":"English",
    "frLabel":"French",
    "esLabel":"Spanish",
    "textParagraph":"Text Paragraph",
    "enTitle":"Enter the paragraph in English",
    "frTitle":"Enter the paragraph in French",
    "esTitle":"Enter the paragraph in Spanish",
    "dropFile":"Drop or Select file",
    "dropDescription":"Drop files here or click browse thorough your machine",
    "textHTitle":"Head Title",
    "enHTitle":"Enter the head title in English",
    "frHTitle":"Enter the head title in French",
    "esHTitle":"Enter the head title in Spanish",
    "headDescription":"Head Description",
    "enHDTitle":"Enter the head description in English",
    "frHDTitle":"Enter the head description in French",
    "esHDTitle":"Enter the head description in Spanish",
    "submit": "Submit",
    "detail": "Detail",
    "main": "main",
  },
  fr: {
    "main": "principale",
    "viewMode": "Mode d'affichage",
    "addNew": "Ajouter un nouveau",
    "viewContents": "Voir le contenu",
    "inputURL":"Entrez l'URL du texte",
    "textTitle": "Titre du texte",
    "enTitle":"Entrez le titre en anglais",
    "frTitle":"Entrez le titre en français",
    "esTitle":"Entrez le titre en espagnol",
    "enLabel":"Anglaise",
    "frLabel":"français",
    "esLabel":"Espanol",
    "textParagraph":"Paragraphe de texte",
    "enTitle":"Entrez le paragraphe en anglais",
    "frTitle":"Entrez le paragraphe en français",
    "esTitle":"Entrez le paragraphe en espagnol",
    "dropFile":"Déposer ou sélectionner un fichier",
    "dropDescription":"Déposez les fichiers ici ou cliquez sur parcourir votre machine",
    "textHTitle":"Titre principal",
    "enHTitle":"Entrez le titre principal en anglais",
    "frHTitle":"Entrez le titre principal en français",
    "esHTitle":"Entrez le titre principal en espagnol",
    "headDescription":"Description de la tête",
    "enHDTitle":"Entrez la description de la tête en anglais",
    "frHDTitle":"Entrez la description de la tête en français",
    "esHDTitle":"Entrez la description de la tête en espagnol",
    "submit": "Soumettre",
    "detail": "Détail",
  },
  es: {
    "main": "principal",
    "viewMode": "Modo de vista",
    "addNew": "Agregar nueva",
    "viewContents": "Ver contenido",
    "inputURL":"Ingrese la URL del texto",
    "textTitle": "Título del texto",
    "enTitle":"Ingrese el título en inglés",
    "frTitle":"Ingrese el título en francés",
    "esTitle":"Ingrese el título en español",
    "enLabel":"Inglesa",
    "frLabel":"Francesa",
    "esLabel":"Española",
    "textParagraph":"Párrafo de texto",
    "enTitle":"Entrez le paragraphe en anglais",
    "frTitle":"Ingrese el párrafo en francés",
    "esTitle":"Ingrese el párrafo en español",
    "dropFile":"Soltar o Seleccionar archivo",
    "dropDescription":"Suelta los archivos aquí o haz clic en navegar a través de tu máquina",
    "textHTitle":"Título de la cabeza",
    "enHTitle":"Ingrese el título de la cabecera en inglés",
    "frHTitle":"Ingrese el título de la cabecera en francés",
    "esHTitle":"Ingrese el título de la cabecera en español",
    "headDescription":"Descripción de la cabeza",
    "enHDTitle":"Ingrese la descripción principal en inglés",
    "frHDTitle":"Ingrese la descripción del encabezado en francés",
    "esHDTitle":"Ingrese la descripción del encabezado en español",
    "submit": "Enviar",
    "detail": "Detalle",
  }
}
